disabled_rules:  # rules you want to exclude
#warnings (There should be a minimum number of excluded warnings in this list)
  - block_based_kvo
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - type_body_length
  - identifier_name

# errors (There should no excluded errors in this list)

# excluded paths
excluded: # paths to exclude
  - Pods

analyzer_rules:
  - unused_import
  - unused_private_declaration

# customized rules

file_name:
  excluded:
  - main.swift

identifier_name:
  min_length: 1
  max_length: 60
  excluded:
  - id

type_name:
  allowed_symbols: _
  max_length: 60
