# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'MovieEnvoy' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for MovieEnvoy
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~>3.5'
  pod 'Kingfisher'
  pod "PromiseKit", "~> 6.0"
  pod 'PromiseKit/Alamofire', '~> 6.0'

  target 'MovieEnvoyTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 4.8'
    pod 'AlamofireImage', '~>3.5'
    pod "PromiseKit", "~> 6.0"
    pod 'PromiseKit/Alamofire', '~> 6.0'
  end

  target 'MovieEnvoyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
