# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MovieEnvoy' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for MovieEnvoy
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~>3.4'

  target 'MovieEnvoyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieEnvoyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
