//
//  MovieEnvoy-Bridging-Header.h
//  MovieEnvoy
//

#define TMDB_BASE_URL TMDB_BASE_URL_DEFINE
#define TMDB_IMAGE_URL TMDB_IMAGE_URL_DEFINE
#define TMDB_API_KEY TMDB_API_KEY_DEFINE

#define ENVIRONMENT_NAME ENVIRONMENT_NAME_DEFINE
